# Generated by Django 4.2.7 on 2023-12-01 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0003_country_alter_plot_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="country",
        ),
    ]
