# Generated by Django 4.2.7 on 2023-12-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0004_remove_plot_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plots",
                to="a_plot.country",
            ),
        ),
    ]
