# Generated by Django 4.2.7 on 2023-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0005_plot_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plot",
            options={"ordering": ["-list_date"]},
        ),
    ]
