# Generated by Django 4.2.7 on 2023-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0006_alter_plot_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="plot",
            name="what3words",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="tags",
            field=models.ManyToManyField(blank=True, to="a_plot.tag"),
        ),
    ]
