# Generated by Django 4.2.7 on 2023-12-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0007_tag_alter_plot_what3words_plot_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="tags",
        ),
        migrations.AddField(
            model_name="plot",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plots",
                to="a_plot.tag",
            ),
        ),
    ]
