# Generated by Django 4.2.7 on 2023-12-16 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a_plot", "0009_tag_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
