# Generated by Django 4.2.7 on 2023-12-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0010_alter_plot_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="categories",
            field=models.IntegerField(
                choices=[(1, "Campsite"), (2, "Official"), (3, "Wild")], default=1
            ),
        ),
    ]
