# Generated by Django 4.2.7 on 2023-12-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0012_alter_plot_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="tags",
        ),
        migrations.AlterField(
            model_name="plot",
            name="campsite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="plot",
            name="categories",
            field=models.CharField(
                choices=[
                    ("Campsite", "Campsite"),
                    ("Official", "Official"),
                    ("Wild", "Wild"),
                ],
                default=1,
                max_length=25,
            ),
        ),
    ]
