# Generated by Django 4.2.7 on 2023-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0015_remove_plot_country_alter_plot_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Mid", "Mid"), ("High", "High")],
                default="Mid",
                max_length=100,
                null=True,
            ),
        ),
    ]
