# Generated by Django 4.2.7 on 2023-12-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a_plot", "0016_plot_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="countries",
            field=models.CharField(
                choices=[
                    ("Spain", "Spain"),
                    ("France", "France"),
                    ("Portugal", "Portugal"),
                    ("Italy", "Italy"),
                    ("Germany", "Germany"),
                    ("Netherlands", "Netherlands"),
                    ("Ireland", "Ireland"),
                    ("Belgium", "Belgium"),
                    ("Greece", "Greece"),
                    ("United Kingdom", "United Kingdom"),
                    ("Switzerland", "Switzerland"),
                    ("Austria", "Austria"),
                    ("Sweden", "Sweden"),
                    ("Norway", "Norway"),
                    ("Finland", "Finland"),
                    ("Denmark", "Denmark"),
                    ("Croatia", "Croatia"),
                    ("Poland", "Poland"),
                    ("Romania", "Romania"),
                    ("Bulgaria", "Bulgaria"),
                    ("Czech Republic", "Czech Republic"),
                    ("Hungary", "Hungary"),
                    ("Slovakia", "Slovakia"),
                    ("Slovenia", "Slovenia"),
                    ("Luxembourg", "Luxembourg"),
                    ("Latvia", "Latvia"),
                    ("Estonia", "Estonia"),
                    ("Lithuania", "Lithuania"),
                    ("Malta", "Malta"),
                    ("Cyprus", "Cyprus"),
                    ("Iceland", "Iceland"),
                    ("Liechtenstein", "Liechtenstein"),
                    ("Monaco", "Monaco"),
                    ("San Marino", "San Marino"),
                    ("Andorra", "Andorra"),
                    ("Albania", "Albania"),
                    ("Armenia", "Armenia"),
                    ("Azerbaijan", "Azerbaijan"),
                    ("Belarus", "Belarus"),
                    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
                    ("Georgia", "Georgia"),
                    ("Kazakhstan", "Kazakhstan"),
                    ("Kosovo", "Kosovo"),
                    ("Macedonia", "Macedonia"),
                    ("Moldova", "Moldova"),
                    ("Montenegro", "Montenegro"),
                    ("Russia", "Russia"),
                    ("Serbia", "Serbia"),
                    ("Turkey", "Turkey"),
                    ("Ukraine", "Ukraine"),
                ],
                default="Spain",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("body", models.CharField(max_length=600)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="a_plot.plot",
                    ),
                ),
            ],
        ),
    ]
