# Generated by Django 4.2.7 on 2023-12-27 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0019_likedpost_plot_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likedpost",
            old_name="post",
            new_name="plot",
        ),
    ]
