# Generated by Django 4.2.7 on 2024-01-03 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0020_likedcomment_comment_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likedcomment",
            old_name="commentt",
            new_name="comment",
        ),
    ]
