# Generated by Django 4.2.7 on 2023-12-27 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a_plot", "0021_rename_likedpost_likedplot_alter_plot_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="likedplot",
            options={},
        ),
        migrations.AlterField(
            model_name="plot",
            name="likes",
            field=models.ManyToManyField(
                related_name="likedplots",
                through="a_plot.LikedPlot",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
