# Generated by Django 4.2.7 on 2024-01-04 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0022_reportplot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportplot",
            old_name="reported_by",
            new_name="user",
        ),
    ]
