# Generated by Django 4.2.7 on 2023-12-27 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0022_alter_likedplot_options_alter_plot_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="likedplot",
            options={"ordering": ["-created"]},
        ),
    ]
