# Generated by Django 4.2.7 on 2024-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0023_rename_reported_by_reportplot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="plot_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
