# Generated by Django 4.2.7 on 2023-12-27 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a_plot", "0023_alter_likedplot_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likedplot",
            unique_together={("plot", "user")},
        ),
    ]
