# Generated by Django 4.2.7 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0024_plot_plot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="plot_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
