# Generated by Django 4.2.7 on 2024-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0025_alter_plot_plot_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="image",
        ),
        migrations.AddField(
            model_name="plot",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Off Topic", "Off Topic"),
                    ("Spam", "Spam"),
                    ("Sexual content", "Sexual content"),
                    ("Nudity", "Nudity"),
                    ("Breaks Rules", "Breaks Rules"),
                    ("Other", "Other"),
                ],
                default="Off Topic",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="reported_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="ReportPlot",
        ),
    ]
