# Generated by Django 4.2.7 on 2024-01-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0025_alter_plot_plot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportplot",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Off Topic", "Off Topic"),
                    ("Spam", "Spam"),
                    ("Sexual content", "Sexual content"),
                    ("Nudity", "Nudity"),
                    ("Breaks Rules", "Breaks Rules"),
                    ("Other", "Other"),
                ],
                default="Off Topic",
                max_length=100,
            ),
        ),
    ]
