# Generated by Django 4.2.7 on 2024-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0026_remove_plot_image_plot_approved_plot_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
