# Generated by Django 4.2.7 on 2024-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0026_alter_reportplot_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
    ]
