# Generated by Django 4.2.7 on 2024-01-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0027_plot_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportplot",
            name="approved",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_reports",
                to="a_plot.plot",
            ),
        ),
    ]
