# Generated by Django 4.2.7 on 2024-01-17 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0027_plot_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="image",
        ),
    ]
