# Generated by Django 4.2.7 on 2024-01-17 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0028_reportplot_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportplot",
            name="approved",
        ),
    ]
