# Generated by Django 4.2.7 on 2024-01-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0028_remove_plot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
