# Generated by Django 4.2.7 on 2024-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0029_alter_plot_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="campsite",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
