# Generated by Django 4.2.7 on 2024-01-17 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0029_remove_reportplot_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="image",
        ),
    ]
