# Generated by Django 4.2.7 on 2024-01-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0030_remove_plot_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportplot",
            name="plot",
        ),
        migrations.AddField(
            model_name="plot",
            name="reported",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="a_plot.reportplot",
            ),
        ),
    ]
