# Generated by Django 4.2.7 on 2023-12-15 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plot",
            new_name="Profile",
        ),
    ]
