# Generated by Django 4.2.7 on 2024-01-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_user", "0005_profile_level_alter_profile_campermode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New SuperCamper", "New SuperCamper"),
                    ("SuperCamper", "SuperCamper"),
                    ("SuperCamper Expert", "SuperCamper Expert"),
                    ("SuperCamper Master", "SuperCamper Master"),
                    ("Restricted SuperCamper", "Restricted SuperCamper"),
                ],
                default="New SuperCamper",
                max_length=30,
                null=True,
            ),
        ),
    ]
