# Generated by Django 4.2.7 on 2024-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_user", "0006_alter_profile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plot_reports",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
