# Generated by Django 4.2.7 on 2024-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_user", "0007_profile_plot_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fav_campsite",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SuperCamper Founder1", "SuperCamper Founder1"),
                    ("SuperCamper Founder2", "SuperCamper Founder2"),
                    ("New SuperCamper", "New SuperCamper"),
                    ("SuperCamper", "SuperCamper"),
                    ("SuperCamper Expert", "SuperCamper Expert"),
                    ("SuperCamper Master", "SuperCamper Master"),
                    ("Restricted SuperCamper", "Restricted SuperCamper"),
                ],
                default="New SuperCamper",
                max_length=30,
                null=True,
            ),
        ),
    ]
